name: test 

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3','7.4']
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Check PHP Version
      run: php -v

    - name: Composer dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

    - name: Run Unit Test
      run: |
        ./vendor/bin/phpunit
      env:
        EGHL_PASSWORD: "password"
        EGHL_SERVICE_ID: "serviceId"
        EGHL_SERVICE_URL: "http://your-eghl-service-url.com"
        MERCHANT_RETURN_URL: "http://your-return-url.com"
        MERCHANT_APPROVAL_URL: "http://your-approval-url.com"
        MERCHANT_UNAPPROVAL_URL: "http://your-unapproval-url.com"
        MERCHANT_CALLBACK_URL: "http://your-callback-url.com"
